version: '3.3'

services:
  ai_auth_server:
    build: ./ai_auth_server
    image: auth_server:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8499:8000"
    env_file:
      - ./ai_auth_server/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1

  ai_scrap_mng_streamlit:
    build: ./ai_scrap_mng_streamlit
    image: ai_scrap_mng_streamlit:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8500:8080"  # 포트 변경docke
    env_file:
      - ./ai_scrap_mng_streamlit/.env
    command: streamlit run run.py --server.port 8080 --server.address 0.0.0.0

  ai_news_scraper:
    build: ./ai_news_scraper
    image: ai_news_scraper:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8501:8080"  # 포트 변경
    env_file:
      - ./ai_news_scraper/.env.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 1

  ai_dart_scraper:
    build: ./ai_dart_scraper
    image: ai_dart_scraper:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8502:8080"  # 포트 변경
    env_file:
      - ./ai_dart_scraper/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 1

  ai_venture_scraper:
    build: ./ai_venture_scraper
    image: ai_venture_scraper:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8503:8080"  # 포트 변경
    env_file:
      - ./ai_venture_scraper/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
    security_opt:
      - seccomp:unconfined

  chrome-node_1:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      selenium-manager: 'true'
      VNC_NO_PASSWORD: 'true'
    security_opt:
      - seccomp:unconfined

  chrome-node_2:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443d
      SE_NODE_MAX_SESSIONS: 4
      VNC_NO_PASSWORD: 'true'
      selenium-manager: 'true'
    security_opt:
      - seccomp:unconfined

  chrome-node_3:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      VNC_NO_PASSWORD: 'true'
      selenium-manager: 'true'
    security_opt:
      - seccomp:unconfined

  chrome-node_4:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      VNC_NO_PASSWORD: 'true'
      selenium-manager: 'true'
    security_opt:
      - seccomp:unconfined
