from app.models.collect_vnia_info import CollectVniaInfo, CollectVniaInfoPydantic
from app.models.collect_vnia_finance_balance import CollectVniaFinanceBalance, CollectVniaFinanceBalancePydantic
from app.models.collect_vnia_finance_income import CollectVniaFinanceIncome, CollectVniaFinanceIncomePydantic
from app.models.collect_vnia_investment_info import CollectVniaInvestmentInfo, CollectVniaInvestmentInfoPydantic
from app.models.collect_vnia_certificate import CollectVniaCertificate, CollectVniaCertificatePydantic
from app.models.new_company_info import NewCompanyInfo, NewCompanyInfoPydantic
